apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-coop
  namespace: podinfo-coop
spec:
  chart:
    spec:
      #version: ">=1.0.0-alpha"
      version: "=6.2.0"
  test:
    enable: false
  values:
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: podinfo-coop.dev.oceanusorigin.com
          paths:
            - path: /
              pathType: ImplementationSpecific
