apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-coop1
  namespace: podinfo-coop
spec:
  chart:
    spec:
      #version: ">=1.0.0-alpha"
      version: "=6.1.8"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: podinfo-coop.dev.oceanusorigin.com
          paths:
            - path: /
              pathType: ImplementationSpecific
